#!/usr/bin/env bash
# Compile tools/online.tsv into assets/js/products-online.js (appends to window.PRODUCTS).
# Uses awk -F'\t' so empty fields (e.g. blank size) are preserved.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=assets/js/products-online.js
{
  echo "// Auto-generated by tools/online-build-js.sh from online category QRs — do not edit by hand."
  echo "window.PRODUCTS = (window.PRODUCTS || []).concat(["
  awk -F'\t' 'NF>=6 {
    slug=$1; code=$2; name=$3; size=$4; coll=$5; fam=$6; sp=$7;
    gsub(/x/,"×",size);
    printf "  { slug: \"%s\", name: \"%s\", code: \"%s\", collection: \"%s\", family: \"%s\", species: \"%s\", size: \"%s\" },\n", slug, name, code, coll, fam, sp, size
  }' tools/online.tsv
  echo "]);"
} > "$OUT"
echo "wrote $(grep -c 'slug:' "$OUT") products to $OUT"
